<?php
/*
 * Navigate Commerce
 *
 * @author        Navigate Commerce
 * @package       Navigate_PasswordHideShow
 * @copyright     Copyright (c) Navigate (https://www.navigatecommerce.com/)
 * @license       https://www.navigatecommerce.com/end-user-license-agreement
 */

$isEditAccount = $block->isEnableForEditAccount();
if ($isEditAccount) {
    $showPasswordImg = '';
    $hidePasswordImg = '';
    if ($block->getShowPasswordImage()) {
        $hidePasswordImg = $block->getShowPasswordImage();
    } else {
        $hidePasswordImg = $block->getViewFileUrl("Navigate_PasswordHideShow::images/eye.png");
    }
    if ($block->getHidePasswordImage()) {
        $showPasswordImg = $block->getHidePasswordImage();
    } else {
        $showPasswordImg = $block->getViewFileUrl("Navigate_PasswordHideShow::images/eye-slash.png");
    }
    ?>
<script>
require(['jquery'], function($){
    jQuery("#current-password").before('<span toggle="#current-password" class="toggle-current-password"><img src="<?= /* @noEscape */ $showPasswordImg ?>" class="eye-open-current" /><img src="<?= /* @noEscape */ $hidePasswordImg ?>" class="eye-close-current" style="display: none;"/></span>'); <?php // phpcs:ignore ?>

    jQuery("#password").before('<span toggle="#password" class="toggle-password"><img src="<?= /* @noEscape */ $showPasswordImg ?>" class="eye-open" /><img src="<?= /* @noEscape */ $hidePasswordImg ?>" class="eye-close" style="display: none;"/></span>'); <?php // phpcs:ignore ?>

    jQuery("#password-confirmation").before('<span toggle="#password-confirmation" class="toggle-password-confirmation"><img src="<?= /* @noEscape */ $showPasswordImg ?>" class="eye-open-confirmation" /><img src="<?= /* @noEscape */ $hidePasswordImg ?>" class="eye-close-confirmation" style="display: none;"/></span>'); <?php // phpcs:ignore ?>

    jQuery("body").on('click', '.toggle-current-password', function() {
        var input = jQuery("#current-password");
        if (input.attr("type") === "password") {
            input.attr("type", "text");
            jQuery(".eye-close-current").show();
            jQuery(".eye-open-current").hide();
        } else {
            jQuery(".eye-close-current").hide();
            jQuery(".eye-open-current").show();
            input.attr("type", "password");
        }
    });

    jQuery("body").on('click', '.toggle-password', function() {
        var input = jQuery("#password");
        if (input.attr("type") === "password") {
            input.attr("type", "text");
            jQuery(".eye-close").show();
            jQuery(".eye-open").hide();
        } else {
            jQuery(".eye-close").hide();
            jQuery(".eye-open").show();
            input.attr("type", "password");
        }
    });
    jQuery("body").on('click', '.toggle-password-confirmation', function() {
        var input = jQuery("#password-confirmation");
        if (input.attr("type") === "password") {
            input.attr("type", "text");
            jQuery(".eye-close-confirmation").show();
            jQuery(".eye-open-confirmation").hide();
        } else {
            jQuery(".eye-close-confirmation").hide();
            jQuery(".eye-open-confirmation").show();
            input.attr("type", "password");
        }
    });
});
</script>
<?php } ?>