<script type="text/javascript">
require(['jquery', 'jquery/ui'], function($){
    jQuery("#pass").before('<span toggle="#pass" class="toggle-password"><img src="<?= $this->getViewFileUrl("Navigate_PasswordHideShow::images/eye.png"); ?>" class="eye-open" /><img src="<?= $this->getViewFileUrl("Navigate_PasswordHideShow::images/eye-slash.png"); ?>" class="eye-close" style="display: none;"/></span>');
    jQuery("body").on('click', '.toggle-password', function() {
        var input = jQuery("#pass");
        if (input.attr("type") === "password") {
            input.attr("type", "text");
            jQuery(".eye-close").show();
            jQuery(".eye-open").hide();
        } else {
            jQuery(".eye-close").hide();
            jQuery(".eye-open").show();
            input.attr("type", "password");
        }
    });
});
</script>